export const TOPIC_KEYWORDS = {
    't01': ['ia', 'intelligence artificielle', 'llm', 'gpt', 'mistral', 'claude', 'machine learning', 'deepseek', 'openai', 'anthropic', 'agent'],
    't02': ['cybersécurité', 'ransomware', 'piratage', 'vulnérabilité', 'sécurité informatique', 'cyberattaque', 'phishing', 'malware', 'zero trust', 'nis2', 'dora'],
    't03': ['cloud', 'transformation digitale', 'dsi', 'erp', 'saas', 'microsoft', 'google', 'numérique', 'logiciel'],
    't04': ['rh', 'recrutement', 'télétravail', 'emploi', 'formation', 'talents', 'management', 'salariés', 'travail'],
    't05': ['bourse', 'marché', 'financement', 'levée', 'capital', 'investissement', 'fonds', 'action', 'cac 40'],
    't06': ['droit', 'juridique', 'loi', 'tribunal', 'contrat', 'réglementation', 'avocat', 'justice'],
    't07': ['esg', 'rse', 'durabilité', 'carbone', 'développement durable', 'csrd', 'green', 'environnement'],
    't08': ['logistique', 'supply chain', 'transport', 'entrepôt', 'livraison', 'stock', 'chaîne'],
    't09': ['marketing', 'publicité', 'seo', 'growth', 'acquisition', 'brand', 'digital', 'campagne'],
    't10': ['management', 'leadership', 'dirigeant', 'équipe', 'organisation', 'culture', 'gouvernance'],
    't11': ['startup', 'innovation', 'levée de fonds', 'french tech', 'licorne', 'incubateur', 'entrepreneur'],
    't12': ['immobilier', 'logement', 'bureau', 'bâtiment', 'loyer', 'construction', 'foncier'],
    't13': ['santé', 'médecine', 'biotech', 'médical', 'hôpital', 'patient', 'thérapie', 'médicament'],
    't14': ['énergie', 'électricité', 'nucléaire', 'solaire', 'éolien', 'hydrogène', 'transition énergétique'],
    't15': ['rgpd', 'compliance', 'conformité', 'réglementation', 'cnil', 'audit', 'dora', 'ai act'],
    't16': ['data', 'données', 'analytics', 'bi', 'intelligence', 'machine learning', 'big data'],
    't17': ['e-commerce', 'retail', 'marketplace', 'vente en ligne', 'commerce', 'amazon', 'fnac'],
    't18': ['géopolitique', 'économie mondiale', 'international', 'europe', 'guerre', 'diplomatie', 'sanctions'],
    't19': ['ux', 'design', 'utilisateur', 'interface', 'expérience', 'prototype', 'figma'],
    't20': ['industrie', 'usine', 'manufacturing', 'robot', 'automatisation', 'lean', 'production'],
}